In [2]:
import pandas as pd
import ast

In [ ]:
df=pd.read_csv(r'D:\Desktop\ML\employee_salary\src\data\raw\us.csv')
df.sample()

,e::Category',"'tag': 'engineering-jobs'}""",215877.61,Adzuna::API::Response::Job,"Position: Research Engineer Location: 100% Remote Duration: Contract Job ID: 178628 Job Overview: 1. 6 years of experience (or equivalent) in research engineering, ML engineering, or systems/software engineering with ML implementation work. 2. Coding background in Python, PyTorch and SQL 3. Publications of their work and experience giving presentations at top conferences showcasing their research 4. Soft Skills - Looking for someone that has a high attention to detail, go-getter personality, te…",5825873821,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsInMiOiI2SUZxZEo2TzhSR0dnT19uMHJtZGlRIn0.MTzIRXgwluf3sKsljPjOF94_Q9dkvrHhWl65LIWmEdE,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'Pinnacle Technical Resources'}",-122.180633,Software Engineer IV,"{'area': ['US', 'California', 'San Mateo County', 'Menlo Park'], 'display_name': 'Menlo Park, San Mateo County', '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/details/5825873821?utm_medium=api&utm_source=70717cc8,2026-08-02T13:28:10Z,215877.61.1,1,Unnamed: 15,Unnamed: 16
174592,NaN,126282.39,{'__CLASS__': 'Adzuna::API::Response::Company'...,Project Manager - Regulatory and SEC Reporting,Role Title: Project Manager - SEC & REG Report...,2026-07-29T17:25:41Z,Adzuna::API::Response::Job,1,126282.39,NaN,5820189263,"{'display_name': 'US', '__CLASS__': 'Adzuna::A...",eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyMDE4OTI2MyIsI...,https://www.adzuna.com/land/ad/5820189263?se=9...,"{'label': 'IT Jobs', '__CLASS__': 'Adzuna::API...",NaN,NaN

In [9]:
df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['    e::Category'', ' 'tag': 'engineering-jobs'}"', '215877.61',
       'Adzuna::API::Response::Job',
       'Position: Research Engineer Location: 100% Remote Duration: Contract Job ID: 178628 Job Overview: 1. 6 years of experience (or equivalent) in research engineering, ML engineering, or systems/software engineering with ML implementation work. 2. Coding background in Python, PyTorch and SQL 3. Publications of their work and experience giving presentations at top conferences showcasing their research 4. Soft Skills - Looking for someone that has a high attention to detail, go-getter personality, te…',
       '5825873821',
       'eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsInMiOiI2SUZxZEo2TzhSR0dnT19uMHJtZGlRIn0.MTzIRXgwluf3sKsljPjOF94_Q9dkvrHhWl65LIWmEdE',
       '{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'Pinnacle Technical Resources'}',
       '-122.180633', 'Software Engineer IV',
       '{'area': ['US', 'California', 'San Mateo County', 'Menlo Park'], 'display_name': 'Menlo Park, San Mateo County', '__CLASS__': 'Adzuna::API::Response::Location'}',
       'https://www.adzuna.com/details/5825873821?utm_medium=api&utm_source=70717cc8',
       '2026-08-02T13:28:10Z', '215877.61.1', '1', 'Unnamed: 15',
       'Unnamed: 16'],
      dtype='str')>

In [10]:
with open(r'D:\Desktop\ML\employee_salary\src\data\raw\us.csv',
          "r",
          encoding="utf-8") as f:

    for i in range(5):
        print(f.readline())

    e::Category', 'tag': 'engineering-jobs'}",215877.61,Adzuna::API::Response::Job,"Position: Research Engineer Location: 100% Remote Duration: Contract Job ID: 178628 Job Overview: 1. 6 years of experience (or equivalent) in research engineering, ML engineering, or systems/software engineering with ML implementation work. 2. Coding background in Python, PyTorch and SQL 3. Publications of their work and experience giving presentations at top conferences showcasing their research 4. Soft Skills - Looking for someone that has a high attention to detail, go-getter personality, te…",5825873821,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsInMiOiI2SUZxZEo2TzhSR0dnT19uMHJtZGlRIn0.MTzIRXgwluf3sKsljPjOF94_Q9dkvrHhWl65LIWmEdE,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'Pinnacle Technical Resources'}",-122.180633,Software Engineer IV,"{'area': ['US', 'California', 'San Mateo County', 'Menlo Park'], 'display_name': 'Menlo Park, San Mateo County', '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/details/5825873821?utm_medium=api&utm_source=70717cc8,2026-08-02T13:28:10Z,215877.61,1,,

42.364083,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::Response::Category', 'label': 'IT Jobs'}",93078.22,Adzuna::API::Response::Job,"Job Title Senior Mainframe Software Engineer (COBOL, DB2, z/OS) Overview We are seeking an experienced Mainframe Software Engineer to support and enhance enterprise mainframe applications while contributing to ongoing modernization initiatives. This role includes application development, production support, defect resolution, customer interaction, and collaboration with cross-functional teams to deliver business-critical solutions and support cloud migration efforts. Key Responsibilities Develo…",5825873792,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3Mzc5MiIsInMiOiI2SUZxZEo2TzhSR0dnT19uMHJtZGlRIn0.sH-4o4UrA_TDv9VTiwD8Ce6CCWJ3K245FIYD811YPpk,"{'display_name': 'HTC Global Services Inc', '__CLASS__': 'Adzuna::API::Response::Company'}",-83.369795,"Senior Mainframe Software Engineer (COBOL, DB2, z/OS)","{'display_name': 'Livonia, Wayne County', 'area': ['US', 'Michigan', 'Wayne County', 'Livonia'], '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/details/5825873792?utm_medium=api&utm_source=70717cc8,2026-08-02T13:27:49Z,93078.22,1,,

38.908569,"{'label': 'IT Jobs', '__CLASS__': 'Adzuna::API::Response::Category', 'tag': 'it-jobs'}",199662.72,Adzuna::API::Response::Job,"The Solutions Architect will design and deliver comprehensive technical solutions that bridge business requirements with scalable, secure application and technology implementations. We know that you can't have great technology services without amazing people. At MetroStar, we are obsessed withour people and have led a two-decade legacy of building the best and brightest teams. Because we know our future relies on our deep understanding and relentless focus on our people, we live by our mission:…",5825873783,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ09fbjBybWRpUSIsImkiOiI1ODI1ODczNzgzIn0.OJQlPY5lbeidkpzfFp-P1wlxGf1PlpOUEae9k_rRdz4,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'MetroStar Systems Inc.'}",-77.017972,Sr. Solutions Architect III (6694) with Security Clearance,"{'area': ['US', 'Washington, D.C.'], 'display_name': 'Washington, D.C., US', '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/land/ad/5825873783?se=6IFqdJ6O8RGGgO_n0rmdiQ&utm_medium=api&utm_source=70717cc8&v=5B11658F8C58107E520919A6159D15DB20FB1E31,2026-08-02T13:27:41Z,199662.72,1,,

33.922235,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLASS__': 'Adzuna::API::Response::Category'}",216432.12,Adzuna::API::Response::Job,"Date Posted: 2026-07-31 Country: United States of America Location: US-CA-EL SEGUNDO-E04 ~ 2006 E El Segundo Blvd ~ BLDG E04 Position Role Type: Onsite U.S. Citizen, U.S. Person, or Immigration Status Requirements: Active and transferable U.S. government issued security clearance is required prior to start date. U.S. citizenship is required, as only U.S. citizens are eligible for a security clearance Security Clearance Type: DoD Clearance: Top Secret Security Clearance Status: Active and existi…",5825873764,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ09fbjBybWRpUSIsImkiOiI1ODI1ODczNzY0In0.bLmfbMyCPojWu9ve2YpEi2oIMxfRk3CMOgUPi6A_6kk,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'RTX'}",-118.405515,"Software Engineer II, Onsite with Security Clearance","{'area': ['US', 'California', 'Los Angeles County', 'El Segundo'], 'display_name': 'El Segundo, Los Angeles County', '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/land/ad/5825873764?se=6IFqdJ6O8RGGgO_n0rmdiQ&utm_medium=api&utm_source=70717cc8&v=7DD13B917C77BFEF09DA0B47584F14A0B1E814EE,2026-08-02T13:27:20Z,216432.12,1,,

47.6829,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLASS__': 'Adzuna::API::Response::Category'}",240462.83,Adzuna::API::Response::Job,"Position: Software Engineer V Location: Redmond, WA, Burlingame, CA, or NYC Duration: 06 months Contract Pay rate: $80-$90/hour on W2 Job ID: 178603 Job Overview: The primary role of a Software Engineer V is to apply principles of computer science and mathematical analysis to the design, development, testing, and evaluation of software and systems that enable computers to function effectively. This position involves researching, designing, developing, and testing operating systems-level softwar…",5825873766,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ09fbjBybWRpUSIsImkiOiI1ODI1ODczNzY2In0.EuxTT-jZDgdUI1Vqdf7vj6pnp9Iv_FiHKNBB6Rdwrgo,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'Pinnacle Technical Resources'}",-122.1209,Software Engineer V,"{'display_name': 'Redmond, King County', 'area': ['US', 'Washington', 'King County', 'Redmond'], '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/details/5825873766?utm_medium=api&utm_source=70717cc8,2026-08-02T13:27:20Z,240462.83,1,,

In [11]:
from pathlib import Path

for file in Path(r"D:\Desktop\ML\employee_salary\src\data\raw").glob("*.csv"):
    with open(file, "r", encoding="utf-8") as f:
        print(file.name)
        print(f.readline())
        print("-" * 80)

au.csv
redirect_url,contract_time,created,salary_is_predicted,title,adref,category,salary_min,location,longitude,description,company,__CLASS__,salary_max,id,latitude,contract_type

--------------------------------------------------------------------------------
ca.csv
title,company,salary_is_predicted,location,redirect_url,latitude,created,description,__CLASS__,id,longitude,adref,category,contract_time,contract_type,salary_min,salary_max

--------------------------------------------------------------------------------
in.csv
company,location,adref,title,category,salary_is_predicted,redirect_url,id,latitude,description,contract_type,created,__CLASS__,longitude,contract_time

--------------------------------------------------------------------------------
mx.csv
category,adref,company,location,title,salary_is_predicted,redirect_url,id,description,latitude,__CLASS__,longitude,created,salary_max,salary_min

--------------------------------------------------------------------------------
nz.csv
__CLASS__,description,category,salary_is_predicted,location,id,redirect_url,created,adref,company,contract_time,title,contract_type,longitude,latitude,salary_min,salary_max

--------------------------------------------------------------------------------
sg.csv
title,__CLASS__,id,description,location,salary_is_predicted,created,adref,company,salary_min,category,redirect_url,salary_max,contract_type,contract_time

--------------------------------------------------------------------------------
us.csv
    e::Category', 'tag': 'engineering-jobs'}",215877.61,Adzuna::API::Response::Job,"Position: Research Engineer Location: 100% Remote Duration: Contract Job ID: 178628 Job Overview: 1. 6 years of experience (or equivalent) in research engineering, ML engineering, or systems/software engineering with ML implementation work. 2. Coding background in Python, PyTorch and SQL 3. Publications of their work and experience giving presentations at top conferences showcasing their research 4. Soft Skills - Looking for someone that has a high attention to detail, go-getter personality, te…",5825873821,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsInMiOiI2SUZxZEo2TzhSR0dnT19uMHJtZGlRIn0.MTzIRXgwluf3sKsljPjOF94_Q9dkvrHhWl65LIWmEdE,"{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'Pinnacle Technical Resources'}",-122.180633,Software Engineer IV,"{'area': ['US', 'California', 'San Mateo County', 'Menlo Park'], 'display_name': 'Menlo Park, San Mateo County', '__CLASS__': 'Adzuna::API::Response::Location'}",https://www.adzuna.com/details/5825873821?utm_medium=api&utm_source=70717cc8,2026-08-02T13:28:10Z,215877.61,1,,

--------------------------------------------------------------------------------

In [12]:
csv_path = RAW_DATA_DIR / f"{country}.csv"

header = not csv_path.exists()

df.to_csv(
    csv_path,
    mode="a",
    index=False,
    header=header
)

NameError: name 'RAW_DATA_DIR' is not defined

In [4]:
df['company']=df['company'].apply(ast.literal_eval)
df['company']=df['company'].apply(lambda x:x['display_name'] )

KeyError: 'company'

In [ ]:
header = "title,company,salary_is_predicted,location,redirect_url,latitude,created,description,__CLASS__,id,longitude,adref,category,contract_time,contract_type,salary_min,salary_max\n"

with open("us.csv", "r", encoding="utf-8") as f:
    data = f.read()

with open("us_fixed.csv", "w", encoding="utf-8") as f:
    f.write(header)
    f.write(data)

In [13]:
import pandas as pd

header = [
    "latitude",
    "category",
    "salary_max",
    "__CLASS__",
    "description",
    "id",
    "adref",
    "company",
    "longitude",
    "title",
    "location",
    "redirect_url",
    "created",
    "salary_min",
    "salary_is_predicted",
    "contract_time",
    "contract_type"
]

df = pd.read_csv(
    r"D:\Desktop\ML\employee_salary\src\data\raw\us.csv",
    names=header,      # Use our own header
    header=None        # Tell pandas the file has no header
)

print(df.head())

df.to_csv(
    r"D:\Desktop\ML\employee_salary\src\data\raw\us_fixed.csv",
    index=False
)

print("US dataset repaired successfully.")

           latitude                                           category  \
0      e::Category'                        'tag': 'engineering-jobs'}"
1         42.364083  {'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...
2         38.908569  {'label': 'IT Jobs', '__CLASS__': 'Adzuna::API...
3         33.922235  {'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...
4           47.6829  {'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...

  salary_max                   __CLASS__  \
0  215877.61  Adzuna::API::Response::Job
1   93078.22  Adzuna::API::Response::Job
2  199662.72  Adzuna::API::Response::Job
3  216432.12  Adzuna::API::Response::Job
4  240462.83  Adzuna::API::Response::Job

                                         description          id  \
0  Position: Research Engineer Location: 100% Rem...  5825873821
1  Job Title Senior Mainframe Software Engineer (...  5825873792
2  The Solutions Architect will design and delive...  5825873783
3  Date Posted: 2026-07-31 Country: United States...  5825873764
4  Position: Software Engineer V Location: Redmon...  5825873766

                                               adref  \
0  eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsI...
1  eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3Mzc5MiIsI...
2  eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...
3  eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...
4  eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...

                                             company    longitude  \
0  {'__CLASS__': 'Adzuna::API::Response::Company'...  -122.180633
1  {'display_name': 'HTC Global Services Inc', '_...   -83.369795
2  {'__CLASS__': 'Adzuna::API::Response::Company'...   -77.017972
3  {'__CLASS__': 'Adzuna::API::Response::Company'...  -118.405515
4  {'__CLASS__': 'Adzuna::API::Response::Company'...    -122.1209

                                               title  \
0                               Software Engineer IV
1  Senior Mainframe Software Engineer (COBOL, DB2...
2  Sr. Solutions Architect III (6694) with Securi...
3  Software Engineer II, Onsite with Security Cle...
4                                Software Engineer V

                                            location  \
0  {'area': ['US', 'California', 'San Mateo Count...
1  {'display_name': 'Livonia, Wayne County', 'are...
2  {'area': ['US', 'Washington, D.C.'], 'display_...
3  {'area': ['US', 'California', 'Los Angeles Cou...
4  {'display_name': 'Redmond, King County', 'area...

                                        redirect_url               created  \
0  https://www.adzuna.com/details/5825873821?utm_...  2026-08-02T13:28:10Z
1  https://www.adzuna.com/details/5825873792?utm_...  2026-08-02T13:27:49Z
2  https://www.adzuna.com/land/ad/5825873783?se=6...  2026-08-02T13:27:41Z
3  https://www.adzuna.com/land/ad/5825873764?se=6...  2026-08-02T13:27:20Z
4  https://www.adzuna.com/details/5825873766?utm_...  2026-08-02T13:27:20Z

  salary_min salary_is_predicted contract_time contract_type
0  215877.61                   1           NaN           NaN
1   93078.22                   1           NaN           NaN
2  199662.72                   1           NaN           NaN
3  216432.12                   1           NaN           NaN
4  240462.83                   1           NaN           NaN
US dataset repaired successfully.

In [14]:
print(df.columns)

Index(['latitude', 'category', 'salary_max', '__CLASS__', 'description', 'id',
       'adref', 'company', 'longitude', 'title', 'location', 'redirect_url',
       'created', 'salary_min', 'salary_is_predicted', 'contract_time',
       'contract_type'],
      dtype='str')

In [15]:
df.head()

,latitude,category,salary_max,__CLASS__,description,id,adref,company,longitude,title,location,redirect_url,created,salary_min,salary_is_predicted,contract_time,contract_type
0,e::Category',"'tag': 'engineering-jobs'}""",215877.61,Adzuna::API::Response::Job,Position: Research Engineer Location: 100% Rem...,5825873821,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3MzgyMSIsI...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-122.180633,Software Engineer IV,"{'area': ['US', 'California', 'San Mateo Count...",https://www.adzuna.com/details/5825873821?utm_...,2026-08-02T13:28:10Z,215877.61,1,NaN,NaN
1,42.364083,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...",93078.22,Adzuna::API::Response::Job,Job Title Senior Mainframe Software Engineer (...,5825873792,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3Mzc5MiIsI...,"{'display_name': 'HTC Global Services Inc', '_...",-83.369795,"Senior Mainframe Software Engineer (COBOL, DB2...","{'display_name': 'Livonia, Wayne County', 'are...",https://www.adzuna.com/details/5825873792?utm_...,2026-08-02T13:27:49Z,93078.22,1,NaN,NaN
2,38.908569,"{'label': 'IT Jobs', '__CLASS__': 'Adzuna::API...",199662.72,Adzuna::API::Response::Job,The Solutions Architect will design and delive...,5825873783,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-77.017972,Sr. Solutions Architect III (6694) with Securi...,"{'area': ['US', 'Washington, D.C.'], 'display_...",https://www.adzuna.com/land/ad/5825873783?se=6...,2026-08-02T13:27:41Z,199662.72,1,NaN,NaN
3,33.922235,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...",216432.12,Adzuna::API::Response::Job,Date Posted: 2026-07-31 Country: United States...,5825873764,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-118.405515,"Software Engineer II, Onsite with Security Cle...","{'area': ['US', 'California', 'Los Angeles Cou...",https://www.adzuna.com/land/ad/5825873764?se=6...,2026-08-02T13:27:20Z,216432.12,1,NaN,NaN
4,47.6829,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...",240462.83,Adzuna::API::Response::Job,Position: Software Engineer V Location: Redmon...,5825873766,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-122.1209,Software Engineer V,"{'display_name': 'Redmond, King County', 'area...",https://www.adzuna.com/details/5825873766?utm_...,2026-08-02T13:27:20Z,240462.83,1,NaN,NaN

In [17]:
df = df.iloc[1:].reset_index(drop=True)

In [18]:
df.to_csv(
    r"D:\Desktop\ML\employee_salary\src\data\raw\repair_us.csv",
    index=False
)