In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'D:\Desktop\ML\employee_salary\src\data\raw\repair_us.csv')

In [3]:
df.head()

,latitude,category,salary_max,__CLASS__,description,id,adref,company,longitude,title,location,redirect_url,created,salary_min,salary_is_predicted,contract_time,contract_type
0,42.364083,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...",93078.22,Adzuna::API::Response::Job,Job Title Senior Mainframe Software Engineer (...,5825873792,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3Mzc5MiIsI...,"{'display_name': 'HTC Global Services Inc', '_...",-83.369795,"Senior Mainframe Software Engineer (COBOL, DB2...","{'display_name': 'Livonia, Wayne County', 'are...",https://www.adzuna.com/details/5825873792?utm_...,2026-08-02T13:27:49Z,93078.22,1,NaN,NaN
1,38.908569,"{'label': 'IT Jobs', '__CLASS__': 'Adzuna::API...",199662.72,Adzuna::API::Response::Job,The Solutions Architect will design and delive...,5825873783,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-77.017972,Sr. Solutions Architect III (6694) with Securi...,"{'area': ['US', 'Washington, D.C.'], 'display_...",https://www.adzuna.com/land/ad/5825873783?se=6...,2026-08-02T13:27:41Z,199662.72,1,NaN,NaN
2,33.922235,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...",216432.12,Adzuna::API::Response::Job,Date Posted: 2026-07-31 Country: United States...,5825873764,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-118.405515,"Software Engineer II, Onsite with Security Cle...","{'area': ['US', 'California', 'Los Angeles Cou...",https://www.adzuna.com/land/ad/5825873764?se=6...,2026-08-02T13:27:20Z,216432.12,1,NaN,NaN
3,47.6829,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...",240462.83,Adzuna::API::Response::Job,Position: Software Engineer V Location: Redmon...,5825873766,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-122.1209,Software Engineer V,"{'display_name': 'Redmond, King County', 'area...",https://www.adzuna.com/details/5825873766?utm_...,2026-08-02T13:27:20Z,240462.83,1,NaN,NaN
4,32.894406,{'__CLASS__': 'Adzuna::API::Response::Category...,169549.98,Adzuna::API::Response::Job,ABOUT ELEMYNT ELEMYNT is an early-stage startu...,5825873554,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-117.20095,Agentic AI Engineer (Xora Portfolio Company),"{'area': ['US', 'California', 'San Diego Count...",https://www.adzuna.com/details/5825873554?utm_...,2026-08-02T13:26:18Z,169549.98,1,full_time,NaN

In [4]:
df.shape

(211834, 17)

In [7]:
import ast
import pandas as pd

def safe_parse(x):
    if pd.isna(x):
        return {}

    if isinstance(x, dict):
        return x

    if isinstance(x, str) and x.strip().startswith("{"):
        try:
            return ast.literal_eval(x)
        except Exception:
            return {}

    return {}

df["company"] = df["company"].apply(safe_parse)

In [8]:
print(type(df.loc[1, "company"]))
print(df.loc[1, "company"])

<class 'dict'>
{'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'MetroStar Systems Inc.'}

In [9]:
df["company_name"] = df["company"].apply(
    lambda x: x.get("display_name")
)

In [10]:
df['company_name'].head()

0         HTC Global Services Inc
1          MetroStar Systems Inc.
2                             RTX
3    Pinnacle Technical Resources
4                 Xora Innovation
Name: company_name, dtype: str

In [11]:
df[["company", "company_name"]].head()

,company,company_name
0,"{'display_name': 'HTC Global Services Inc', '_...",HTC Global Services Inc
1,{'__CLASS__': 'Adzuna::API::Response::Company'...,MetroStar Systems Inc.
2,{'__CLASS__': 'Adzuna::API::Response::Company'...,RTX
3,{'__CLASS__': 'Adzuna::API::Response::Company'...,Pinnacle Technical Resources
4,{'__CLASS__': 'Adzuna::API::Response::Company'...,Xora Innovation

In [14]:
df['category']=df['category'].apply(safe_parse)

In [15]:
type(df.loc[1,'category'])

dict

In [17]:
df['category_name']=df['category'].apply(
    lambda x:x.get('label')
)
df['category_tag']=df['category'].apply(
    lambda x: x.get('tag')
)

In [18]:
df[['category_name','category_tag']].head()

  category_name category_tag
0       IT Jobs      it-jobs
1       IT Jobs      it-jobs
2       IT Jobs      it-jobs
3       IT Jobs      it-jobs
4       IT Jobs      it-jobs

In [19]:
df.head(2)

,latitude,category,salary_max,__CLASS__,description,id,adref,company,longitude,title,location,redirect_url,created,salary_min,salary_is_predicted,contract_time,contract_type,company_name,category_name,category_tag
0,42.364083,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...",93078.22,Adzuna::API::Response::Job,Job Title Senior Mainframe Software Engineer (...,5825873792,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgyNTg3Mzc5MiIsI...,"{'display_name': 'HTC Global Services Inc', '_...",-83.369795,"Senior Mainframe Software Engineer (COBOL, DB2...","{'display_name': 'Livonia, Wayne County', 'are...",https://www.adzuna.com/details/5825873792?utm_...,2026-08-02T13:27:49Z,93078.22,1,NaN,NaN,HTC Global Services Inc,IT Jobs,it-jobs
1,38.908569,"{'label': 'IT Jobs', '__CLASS__': 'Adzuna::API...",199662.72,Adzuna::API::Response::Job,The Solutions Architect will design and delive...,5825873783,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNklGcWRKNk84UkdHZ...,{'__CLASS__': 'Adzuna::API::Response::Company'...,-77.017972,Sr. Solutions Architect III (6694) with Securi...,"{'area': ['US', 'Washington, D.C.'], 'display_...",https://www.adzuna.com/land/ad/5825873783?se=6...,2026-08-02T13:27:41Z,199662.72,1,NaN,NaN,MetroStar Systems Inc.,IT Jobs,it-jobs

In [20]:
df['location']=df['location'].apply(safe_parse)

In [21]:
df['location_name']=df['location'].apply(
    lambda x:x.get('display_name')
)

In [24]:
df['location_area']=df['location'].apply(
    lambda x:x.get('area')
)

In [25]:
df[['location_area','location_name']].head(2)

                           location_area          location_name
0  [US, Michigan, Wayne County, Livonia]  Livonia, Wayne County
1                 [US, Washington, D.C.]   Washington, D.C., US

In [26]:
df['country']=df['location_area'].apply(
    lambda x: x[0] if isinstance(x,list) and len(x)>0 else None
)
df['State']=df['location_area'].apply(
    lambda x:x[1] if isinstance(x,list) and len(x)>1 else None
)
df["county"] = df["location_area"].apply(
    lambda x: x[2] if isinstance(x, list) and len(x) > 2 else None
)

df["city"] = df["location_area"].apply(
    lambda x: x[-1] if isinstance(x, list) and len(x) > 0 else None
)

In [28]:
df[
    [
        "company_name",
        "category_name",
        "category_tag",
        "country",
        "State",
        "county",
        "city"
    ]
].head()

,company_name,category_name,category_tag,country,State,county,city
0,HTC Global Services Inc,IT Jobs,it-jobs,US,Michigan,Wayne County,Livonia
1,MetroStar Systems Inc.,IT Jobs,it-jobs,US,"Washington, D.C.",NaN,"Washington, D.C."
2,RTX,IT Jobs,it-jobs,US,California,Los Angeles County,El Segundo
3,Pinnacle Technical Resources,IT Jobs,it-jobs,US,Washington,King County,Redmond
4,Xora Innovation,IT Jobs,it-jobs,US,California,San Diego County,La Jolla

In [29]:
df.drop(
    columns=[
        "company",
        "category",
        "location"
    ],
    inplace=True
)

In [30]:
df.to_csv(r'D:\Desktop\ML\employee_salary\src\data\raw\us.csv',index=False)